# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('about', '0001_initial'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
