# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagelanding_landing_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='intro',
        ),
    ]
