# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagemarketing',
            old_name='market_button',
            new_name='market_desc',
        ),
    ]
