# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='sub_heading',
        ),
    ]
